
version: "2.2"

services:

 apache:

   container_name: apache_pacheco
   image: httpd:latest
   ports:
     - 80:80
   networks:
      br02:
        ipv4_address: 10.1.0.4
   volumes:
     - apache-data:/usr/local/apache2/conf
     - apache-data2:/usr/local/apache2/htdocs

 bind9:
   container_name: dns_pacheco
   image: internetsystemsconsortium/bind9:9.16
   networks:
      br02:
        ipv4_address: 10.1.0.35 
   volumes:
    - dns_web_apache:/var/lib/docker/volumes/dns_web_apache/_data
  
 asir_cliente:
   container_name: cliente_apache_pacheco
   image: kasmweb/desktop:1.9.0
   ports:
    - 6901:6901
   environment:
    VNC_PW: "password"
   networks:
      br02:

volumes:
 apache-data:
   external: true
 apache-data2:
   external: true
 dns_web_apache:
   external: true

networks:
  br02:
    external: true 